controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute


register:
    path: /register
    controller: App\Controller\RegistrationController::index

login:
    path: /login
    controller: App\Controller\LoginController::index

logout:
    path: /logout
    controller: App\Controller\SecurityController::logout
